name: Build Application

on:
  push:
    branches-ignore:
      - 'stable'
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:

jobs:

  build_debug:
    name: Build RelWithDebInfo
    uses: ./.github/workflows/build.yml
    with:
      build_type: RelWithDebInfo
